### ISSUE TITLE
Pivot! How many days until X holiday

### ISSUE THREAD

**Issue by M0nica** [M0nica/how-many-days-until#13]
Allow users to see how many days away the next US Federal Holiday is.

Display copy such as:

The next holiday is [HOLIDAY] which is [#] days away.

https://www.redcort.com/us-federal-bank-holidays/

Discussion
Should we include holidays like:
Halloween, April Fools Day, etc.

Future
- Include International holidays and/or localize

**Comment by M0nica** [comment]
@r-i-c-h I think the dates could be hard-coded for V1 and then would want to have a follow up at some point to programmatically get the data

**Comment by zarasyversen** [comment]
I'm happy to try and add Christmas 🎅 ! Would you like it to be on the same page? Like sitting underneath the current NYE one or on a new page?

**Comment by M0nica** [comment]
@zarasyversen I think it would be great if you added a new page for Christmas -- thanks! I think that's a good approach.

**Comment by cori** [comment]
How would you feel about using an API to resolve interesting dates that aren't static? Specifically I'm thinking about implementing Days to Winter Solstice using http://aa.usno.navy.mil/data/docs/api.php#seasons but it could be extended to calculate lunar dates like those for Jewish holidays or the next full moon as well.
