### ISSUE TITLE
Bad README.md

### ISSUE THREAD

**Issue by r-i-c-h** [M0nica/how-many-days-until#16]
Current Repo README.md is the stock from `create-react-app` and does not describe the project at all

**Comment by M0nica** [comment]
@r-i-c-h what recommendations do you have for improving the README. Currently, it has a brief description as the project is still taking shape.

**Comment by cori** [comment]
One thing I ran into is that I had to run `npm install` before attempting `npm start`. I'm mostly a Node / NPM newbie so maybe I'm doing it wrong, but what I had to do seems pretty consistent with my few other experiences.

**Comment by r-i-c-h** [comment]
@cori  - Don't worry, that is the way it is supposed to work. You're doing great.

Instead of everyone saving and downloading every single file from the `node_modules` folder back and forth to github, instead we all just use the same small `package.json` file. 
When you type `npm install` you are telling npm to open up the closest package.json and install everything listed. Really, this comes into play with making sure everyone is using the exact same versions of the different libraries, or if, say, I already have my own copy of some library, there's no need to re-download it if I don't want to. 

The node_modules folder should always be ignored by git, which it is in the `.gitignore` file.

**Comment by cori** [comment]
That's absolutely what I expected - I just wasn't sure if for some reason I didn't need the `npm install` step since it wasn't called out in the README, and I didn't want to be making a specious update to the docs if I just had the wrong end of the stick somehow.

Thanks for the confirmation!
