### ISSUE TITLE
Add picture to README

### ISSUE THREAD

**Issue by M0nica** [M0nica/how-many-days-until#19]
Add a screenshot of the current app to README or add a graphic that represents the website to the README.

**Comment by chaluvadis** [comment]
I will submit the pull request for this.

**Comment by M0nica** [comment]
Hi @chaluvadis! Someone else submitted a PR for this change. However, changes to the README can be made by forking this repository as opposed to trying to edit it directly. Is there another small change you'd to make to the README.

https://help.github.com/articles/fork-a-repo/

**Comment by chaluvadis** [comment]
I didnt see that. I submitted a pull request.
