### ISSUE TITLE
Make CSS Improvements 

### ISSUE THREAD

**Issue by M0nica** [M0nica/how-many-days-until#23]
- Any ideas for how this website can look better? 

I like how https://hacktoberfest.lingonsaft.com/ if that's any inspiration.

Multiple people are welcome to work on this and open issues :) 

<img width="1401" alt="screen shot 2018-10-11 at 9 44 26 pm" src="https://user-images.githubusercontent.com/6998954/46843027-e973b000-cd9e-11e8-9c5a-64fb60077473.png">

**Comment by maafaishal** [comment]
The project is still not good responsive on mobile. I will try to fix it.

**Comment by KumarManoj-S** [comment]
Can you be more specific?

**Comment by dekisr** [comment]
Ok,
