### ISSUE TITLE
Add ability to switch pages/views

### ISSUE THREAD

**Issue by M0nica** [M0nica/how-many-days-until#29]
In this PR https://github.com/M0nica/how-many-days-until/pull/27/ a Christmas countdown component was added. We need to add the ability to switch pages/vies this can be achieved by:

- giving Christmas a seperate route and linking to that route
- setting state that determines if Christmas or New Year's countdown should be displayed. It can default to New Year's countdown. This is the more React way imo.

**Comment by MicroDroid** [comment]
How about I implement a configuration key that switches between different modes?

Meaning, you can configure it to show how many days until 2019, or Christmas, etc.

What do you think?

**Comment by deecewan** [comment]
I'll take a crack at this.

**Comment by aarai** [comment]
Added routing Home, Christmas and new years views. Please let me know if this is what you had in mind.
#33
