### ISSUE TITLE
Fix Flow type errors in App.js

### ISSUE THREAD

**Issue by M0nica** [M0nica/how-many-days-until#38]
```/Users/xxxx/Dev/how-many-days-until/src/App.js
  9:1  error  Type identifier 'State' does not match pattern '/^([A-Z][a-z0-9]+)+Type$/'  flowtype/type-id-match

```
Verify issue locally by running  `npm run lint`. When it is resolved the error should no longer appear when you run `npm run lint`

Flow is a static type checker for JavaScript https://flow.org/

**Comment by danmakenoise** [comment]
I can take this!
