### ISSUE TITLE
Fix linting issue

### ISSUE THREAD

**Issue by M0nica** [M0nica/how-many-days-until#9]
Update `dateHelper.js` to eliminate this error. 

```./src/util/dateHelpers.js
  Line 25:  Expected '===' and instead saw '=='  eqeqeq
```

**Comment by Ilyeo** [comment]
@M0nica could I take this issue?

**Comment by M0nica** [comment]
This issue was just closed @Ilyeo. Would you be interested in working on https://github.com/M0nica/how-many-days-until/issues/8? Or is there another enhancement you would like to work on?
